### ISSUE TITLE
Fazer uma interface gráfica

### ISSUE THREAD

**Issue by durvalcarvalho** [Testes-de-Software-Confiabilidade/issues-dataset-generator#10]
Fazer um site que permita qualquer usuário definir o nome do repositório, o token do github, as issues e com base nesses dados gerar o dataset e mostrar os gráficos

**Comment by sofiapatrocinio** [comment]
Protótipo
https://www.figma.com/file/vFYKrIkwIkZy4MUODlGwHg/Untitled?node-id=0:1

**Comment by sofiapatrocinio** [comment]
Aplicação Deployada:
https://reliability-app.netlify.app
